### ISSUE TITLE
[Feature Request] Support Bitbucket repositories

### ISSUE THREAD

**Issue by moderndeveloperllc** [phalconist/phalconist#5]
I have my repos over on Bitbucket:

https://bitbucket.org/moderndeveloperllc/phalconscrypt
https://bitbucket.org/moderndeveloperllc/phalconlocale

I would love to have them used as resources by the community if possible. They are in packagist as these URLs, so I don't really want to change them to Github.

**Comment by serebro** [comment]
Thank you for your suggestion.
We do not intend to add support for bitbucket.
You can implement it and we'll add it to phalconist.
