### ISSUE TITLE
ElasticSearch 1.5.2 error

### ISSUE THREAD

**Issue by joglomedia** [phalconist/phalconist#6]
Hi,

i am trying phalconist on my local machine, with Elasticsearch 1.5.2 (i am new to this one)

I get error,

"SearchPhaseExecutionException[Failed to execute phase [query], all shards failed; shardFailures ..... "

detailed error message is here http://pastebin.com/eNfn515T

is there any suggestion?

thanks in advance

**Comment by ovr** [comment]
Maybe this fails

* Db empty (try to phalconist.com/add)

Via server is using 

```
{
  "status" : 200,
  "name" : "Briquette",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "1.5.2",
    "build_hash" : "62ff9868b4c8a0c45860bebb259e21980778ab1c",
    "build_timestamp" : "2015-04-27T09:21:06Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.4"
  },
  "tagline" : "You Know, for Search"
}
```

**Comment by joglomedia** [comment]
shame on me,

i have able to run it now, using the console tool provided 
console.sh main init :D

thanks

**Comment by ovr** [comment]
Okey, super
