### ISSUE TITLE
Github login on https://phalconist.com/ failing

### ISSUE THREAD

**Issue by ninjapanzer** [phalconist/phalconist#9]
It doesn't appear the error is related to an incorrectly configured request process. I suspect it is because of incorrect client credentials.
`https://github.com/login/oauth/authorize?client_id=3ca99ce1184766879cbb&redirect_uri=http%3A%2F%2Fphalconist.com%2Foauth%2Fgithub%3Fprovider%3Dgithub`
<img width="1367" alt="screen shot 2017-07-08 at 12 22 05 am" src="https://user-images.githubusercontent.com/159591/27982590-889654fe-6373-11e7-91d7-e100201a8d73.png">

**Comment by sergeyklay** [comment]
Cc @ovr

**Comment by ovr** [comment]
I will take a look

**Comment by ovr** [comment]
Should be fixed now 🍾

**Comment by ovr** [comment]
@sergeyklay can you give me access to `phalconist` repository? Thank

**Comment by sergeyklay** [comment]
@ovr Done. I'm still on vacation, sorry for delay

**Comment by sergeyklay** [comment]
Fixed. Thank you for the report, and for helping us make Phalcon better.
